---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: foreman
      tier: cache
  template:
    metadata:
      name: redis
      labels:
        app: foreman
        tier: cache
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379